### ISSUE TITLE
Support for queues

### ISSUE THREAD

**Issue by afortiorama** [HEP-Puppet/arc_ce#33]
Hi,

I've changed a bit support for queues. The main two changes are

* I've removed the cluster authorizedvo default values in the class because they override those on a per queue basis.
* I've changed the current handling to just another template snapshot rather than an extra class creating a resources. The template then just loops on an hash of queues in this way

```
<% @queues.each_pair do |queue_name, queue_data| %>
[queue/<%= queue_name -%>]
name="<%= queue_name -%>"
<% if queue_data['default_memory'] -%>
defaultmemory=<%= queue_data['default_memory'] %>
<% end -%>
<% if queue_data['comment'] -%>
comment="<%= queue_data['comment'] -%>"
[.....]
<% end -%>
```
I've put the template in a file called queues.erb instead of queue.erb to avoid overriding completely the previous method. The hiera snapshot is like before with some extra parameters even if they are not in the a-rex schema they can be used see time limits later.

```
arc_ce::queues:
  long:
    default_memory: '2048'
    maxwalltime: 4320
    defaultwallt: 1440
    maxcputime: 4320
    defaultcput: 1440
    cpudistribution:
      - '8cpu:2'
    homogeneity: false
    condor_requirements: "(Opsys == \"linux\") && (OpSysMajorVer == 7)"
    authorized_vos:
      - atlas
      - vo.northgrid.ac.uk
    ac_policy: true
medium
[.....]
```
* I've added support for arc-vomsac-check in the grid-manager template

```
authplugin="ACCEPTED timeout=60,onfailure=fail,onsuccess=pass %W/libexec/arc/arc-vomsac-check -L %C/job.%I.local -P %C/job.%I.proxy"
```

* I've modified Condor.pm to collect max and default walltime and cputime information from arc.conf rather than adding fixed numbers I followed the convetion and stored it in condor.pm.ARC.5.4.1. The code I've added is 

```
my %queue_ei= queue_extra_info($qname);

    $lrms_queue{maxwalltime} = $queue_ei{maxwalltime} || '';
    $lrms_queue{minwalltime} = $queue_ei{minwalltime} || '';
    $lrms_queue{defaultwallt} = $queue_ei{defaultwallt} || '';
    $lrms_queue{maxcputime} = $queue_ei{maxcputime} || '';
    $lrms_queue{mincputime} = $queue_ei{mincputime} || '';
    $lrms_queue{defaultcput} = $queue_ei{defaultcput} || '';

    $lrms_queue{status} = 1;
    return %lrms_queue;
}

sub queue_extra_info($){
    require ConfigParser;
    my $qname = shift;

    my $parser = ConfigParser->new($arcconf)
        or die "Cannot parse $arcconf config file";
    return $parser->get_section("queue/$qname")
}
```
The latter snapshot of code still doesn't work as it should because somehow in the manipulation of the hashes the other ARC scripts retain the values only of the first queue. I need to dig a bit more to see how to fix that.

 The code is in https://github.com/afortiorama/arc_ce
